name: squad

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python==3.8.6
  - pip==20.3.3
  - numpy==1.19.5
  - pandas==1.2.0
  - matplotlib==3.3.3
  - scipy==1.6.0
  - ipykernel==5.4.2
  - pytorch==1.7.1
  - gensim==3.8.3
  - transformers==4.2.1
  - pip:
      - black==20.8b1
      - nltk==3.5
      - wandb==0.10.14
